Treewide: proper check command errors in init script

diff --git a/board/falcon/rootfs/etc/init.d/S50mtsched b/board/falcon/rootfs/etc/init.d/S50mtsched
--- a/board/falcon/rootfs/etc/init.d/S50mtsched
+++ b/board/falcon/rootfs/etc/init.d/S50mtsched
@@ -3,29 +3,35 @@
 #!/bin/sh
 
 start() {
-	printf 'Set MIPS mtsched: '
+    printf 'Set MIPS mtsched: '
 
-	echo "t0 0x0" > /proc/mips/mtsched
-	echo "t1 0x1" > /proc/mips/mtsched
-	echo "v0 0x0" > /proc/mips/mtsched
+     (
+        # Check if command fails
+        set -e && set -o pipefail
 
-	status=$?
-	if [ "$status" -eq 0 ]; then
-		echo "OK"
-	else
-		echo "FAIL"
-	fi
-	return "$status"
+        # Set mtsched
+        echo "t0 0x0" > /proc/mips/mtsched
+        echo "t1 0x1" > /proc/mips/mtsched
+        echo "v0 0x0" > /proc/mips/mtsched
+    )
+
+    status=$?
+    if [ "$status" -eq 0 ]; then
+        echo "OK"
+    else
+        echo "FAIL"
+    fi
+    return "$status"
 }
 
 case "$1" in
-	start|reload|restart)
-		"$1";;
-	stop)
-		# Nothing to do
-		;;
-	*)
-		echo "Usage: $0 {start|stop|restart|reload}"
-		exit 1
+    start|reload|restart)
+        "$1";;
+    stop)
+        # Nothing to do
+        ;;
+    *)
+        echo "Usage: $0 {start|stop|restart|reload}"
+        exit 1
 esac
 
diff --git a/package/mdev-static/S10mdev b/package/mdev-static/S10mdev
--- a/package/mdev-static/S10mdev
+++ b/package/mdev-static/S10mdev
@@ -3,71 +3,75 @@
 #!/bin/sh
 
 start() {
-	printf 'Starting mdev: '
+    printf 'Starting mdev: '
 
-	# Umount early static /dev
-	umount /dev/pts /dev/shm /dev >/dev/null 2>&1
+    (
+        # Check if command fails
+        set -e && set -o pipefail
 
-	# Mount tmpfs for /dev
-	mount -n -t tmpfs -o "exec,nosuid,mode=0755,size=64k" mdev-tmpfs /dev
+        # Umount early static /dev
+        umount /dev/pts /dev/shm /dev >/dev/null 2>&1 || true
 
-	# Enable hotplug event serialization
-	touch /dev/mdev.seq
+        # Mount tmpfs for /dev
+        mount -n -t tmpfs -o "exec,nosuid,mode=0755,size=64k" mdev-tmpfs /dev
 
-	# Create basic nodes
-	ln -snf /proc/self/fd /dev/fd
-	ln -snf fd/0 /dev/stdin
-	ln -snf fd/1 /dev/stdout
-	ln -snf fd/2 /dev/stderr
-	mkdir -m 0755 /dev/pts /dev/shm
+        # Enable hotplug event serialization
+        touch /dev/mdev.seq
 
-	# Set mdev as hotplug agent helper
-	echo /sbin/mdev > /proc/sys/kernel/hotplug
+        # Create basic nodes
+        ln -snf /proc/self/fd /dev/fd
+        ln -snf fd/0 /dev/stdin
+        ln -snf fd/1 /dev/stdout
+        ln -snf fd/2 /dev/stderr
+        mkdir -m 0755 /dev/pts /dev/shm
 
-	# Start scan and populate /dev
-	/sbin/mdev -s
+        # Set mdev as hotplug agent helper
+        echo /sbin/mdev > /proc/sys/kernel/hotplug
 
-	# Mount /dev/pts /dev/shm
-	mount /dev/pts
-	mount /dev/shm
+        # Start scan and populate /dev
+        /sbin/mdev -s
 
-	status=$?
-	if [ "$status" -eq 0 ]; then
-		echo "OK"
-	else
-		echo "FAIL"
-	fi
-	return "$status"
+        # Mount /dev/pts /dev/shm
+        mount /dev/pts
+        mount /dev/shm
+    )
+
+    status=$?
+    if [ "$status" -eq 0 ]; then
+        echo "OK"
+    else
+        echo "FAIL"
+    fi
+    return "$status"
 }
 
 stop() {
-	printf 'Stopping mdev: '
+    printf 'Stopping mdev: '
 
-	echo '' > /proc/sys/kernel/hotplug
+    echo '' > /proc/sys/kernel/hotplug
 
-	status=$?
-	if [ "$status" -eq 0 ]; then
-		rm -f "$PIDFILE"
-		echo "OK"
-	else
-		echo "FAIL"
-	fi
-	return "$status"
+    status=$?
+    if [ "$status" -eq 0 ]; then
+        echo "OK"
+    else
+        echo "FAIL"
+    fi
+    return "$status"
 }
 
 restart() {
-	stop
-	sleep 1
-	start
+    stop
+    sleep 1
+    start
 }
 
 case "$1" in
-	start|stop|restart)
-		"$1";;
-	reload)
-		# Restart, since there is no true "reload" feature.
-		restart;;
-	*)
-		echo "Usage: $0 {start|stop|restart|reload}"
-		exit 1
+    start|stop|restart)
+        "$1";;
+    reload)
+        # Restart, since there is no true "reload" feature.
+        restart;;
+    *)
+        echo "Usage: $0 {start|stop|restart|reload}"
+        exit 1
 esac
